plugins {
    id 'java'
}

group = 'com.cubex'
version = '1.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly files('libs/paper-api.jar')
    compileOnly files('libs/annotations.jar')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

processResources {
    from('src/main/resources') {
        include '**/*'
    }
}

jar {
    archiveBaseName.set('LetMeAsk')
    archiveVersion.set('1.1.0')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
